In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
veriler = pd.read_csv('odev_tenis.csv')

In [4]:
veriler.head()

    outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [5]:
play = veriler.iloc[:,4:].values
play

array([['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no']], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
veriler2 = veriler.apply(LabelEncoder().fit_transform)

In [8]:
veriler2

    outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [9]:
c = veriler2.iloc[:,:1]
c

    outlook
0         2
1         2
2         0
3         1
4         1
5         1
6         0
7         2
8         2
9         1
10        2
11        0
12        0
13        1

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
c = ohe.fit_transform(c).toarray()
c

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [11]:
veriler.head()

    outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [12]:
havadurumu = pd.DataFrame(data=c , index=range(14) , columns=['overcast' , 'rainy' , 'sunny'])
havadurumu

    overcast  rainy  sunny
0        0.0    0.0    1.0
1        0.0    0.0    1.0
2        1.0    0.0    0.0
3        0.0    1.0    0.0
4        0.0    1.0    0.0
5        0.0    1.0    0.0
6        1.0    0.0    0.0
7        0.0    0.0    1.0
8        0.0    0.0    1.0
9        0.0    1.0    0.0
10       0.0    0.0    1.0
11       1.0    0.0    0.0
12       1.0    0.0    0.0
13       0.0    1.0    0.0

In [13]:
sonveriler = pd.concat([havadurumu , veriler.iloc[:,1:3]] , axis=1)
sonveriler = pd.concat([veriler2.iloc[:,-2:] , sonveriler] , axis=1)
sonveriler

    windy  play  overcast  rainy  sunny  temperature  humidity
0       0     0       0.0    0.0    1.0           85        85
1       1     0       0.0    0.0    1.0           80        90
2       0     1       1.0    0.0    0.0           83        86
3       0     1       0.0    1.0    0.0           70        96
4       0     1       0.0    1.0    0.0           68        80
5       1     0       0.0    1.0    0.0           65        70
6       1     1       1.0    0.0    0.0           64        65
7       0     0       0.0    0.0    1.0           72        95
8       0     1       0.0    0.0    1.0           69        70
9       0     1       0.0    1.0    0.0           75        80
10      1     1       0.0    0.0    1.0           75        70
11      1     1       1.0    0.0    0.0           72        90
12      0     1       1.0    0.0    0.0           81        75
13      1     0       0.0    1.0    0.0           71        91

## Veri ön işleme bitti

In [14]:
sonveriler.iloc[:,:-1]

    windy  play  overcast  rainy  sunny  temperature
0       0     0       0.0    0.0    1.0           85
1       1     0       0.0    0.0    1.0           80
2       0     1       1.0    0.0    0.0           83
3       0     1       0.0    1.0    0.0           70
4       0     1       0.0    1.0    0.0           68
5       1     0       0.0    1.0    0.0           65
6       1     1       1.0    0.0    0.0           64
7       0     0       0.0    0.0    1.0           72
8       0     1       0.0    0.0    1.0           69
9       0     1       0.0    1.0    0.0           75
10      1     1       0.0    0.0    1.0           75
11      1     1       1.0    0.0    0.0           72
12      0     1       1.0    0.0    0.0           81
13      1     0       0.0    1.0    0.0           71

In [27]:
sonveriler.iloc[:,-1:]

    humidity
0         85
1         90
2         86
3         96
4         80
5         70
6         65
7         95
8         70
9         80
10        70
11        90
12        75
13        91

In [15]:
from sklearn.model_selection import train_test_split     #bağımsız
x_train , x_test , y_train , y_test = train_test_split(sonveriler.iloc[:,:-1] 
                                                       #bağımlı
                                                       ,sonveriler.iloc[:,-1:]
                                                       ,test_size=0.33
                                                        ,random_state=0)

In [16]:
x_train

    windy  play  overcast  rainy  sunny  temperature
13      1     0       0.0    1.0    0.0           71
9       0     1       0.0    1.0    0.0           75
1       1     0       0.0    0.0    1.0           80
7       0     0       0.0    0.0    1.0           72
10      1     1       0.0    0.0    1.0           75
3       0     1       0.0    1.0    0.0           70
0       0     0       0.0    0.0    1.0           85
5       1     0       0.0    1.0    0.0           65
12      0     1       1.0    0.0    0.0           81

In [17]:
x_test

    windy  play  overcast  rainy  sunny  temperature
8       0     1       0.0    0.0    1.0           69
6       1     1       1.0    0.0    0.0           64
4       0     1       0.0    1.0    0.0           68
11      1     1       1.0    0.0    0.0           72
2       0     1       1.0    0.0    0.0           83

In [18]:
y_train

    humidity
13        91
9         80
1         90
7         95
10        70
3         96
0         85
5         70
12        75

In [19]:
y_test

    humidity
8         70
6         65
4         80
11        90
2         86

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train , y_train)

LinearRegression()

In [21]:
y_pred = regressor.predict(x_test)
y_pred , y_test

(array([[84.45365573],
        [63.93839954],
        [85.76050662],
        [64.21013241],
        [75.06793322]]),
     humidity
 8         70
 6         65
 4         80
 11        90
 2         86)

In [22]:
sonveriler.iloc[:,:-1]

    windy  play  overcast  rainy  sunny  temperature
0       0     0       0.0    0.0    1.0           85
1       1     0       0.0    0.0    1.0           80
2       0     1       1.0    0.0    0.0           83
3       0     1       0.0    1.0    0.0           70
4       0     1       0.0    1.0    0.0           68
5       1     0       0.0    1.0    0.0           65
6       1     1       1.0    0.0    0.0           64
7       0     0       0.0    0.0    1.0           72
8       0     1       0.0    0.0    1.0           69
9       0     1       0.0    1.0    0.0           75
10      1     1       0.0    0.0    1.0           75
11      1     1       1.0    0.0    0.0           72
12      0     1       1.0    0.0    0.0           81
13      1     0       0.0    1.0    0.0           71

In [23]:
import statsmodels.api as sm
X = np.append(arr= np.ones((14,1)).astype(int)
              ,values=sonveriler.iloc[:,:-1] , axis=1)

In [24]:
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values
               #Bağımlı                        #Bağımsız
r_ols = sm.OLS(endog= sonveriler.iloc[:,-1:] , exog = X_l )
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Thu, 31 Jul 2025   Prob (F-statistic):              0.661
Time:                        20:48:25   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x2            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x3            52.3891     50.214      1.043      0.327     -63.404     168.183
x4            55.6337     45.233      1.230      0.254     -48.673     159.940
x5            49.4291     48.337      1.023      0.336     -62.035     160.893
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

c:\Users\erena\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\stats\_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=14 observations were given.
  return hypotest_fun_in(*args, **kwds)

In [25]:
# p_value'ları en yüksek olanları listeden çıkartıyoruz.

sonveriler = sonveriler.iloc[:,1:]

X = np.append(arr= np.ones((14,1)).astype(int)
              ,values=sonveriler.iloc[:,:-1] , axis=1)

X_l = sonveriler.iloc[:,[0,1,2,3,4,]].values
               #Bağımlı                        #Bağımsız
r_ols = sm.OLS(endog= sonveriler.iloc[:,-1:] , exog = X_l )
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Thu, 31 Jul 2025   Prob (F-statistic):              0.546
Time:                        20:48:25   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x2            36.6564     39.905      0.919      0.382     -53.615     126.927
x3            41.9135     36.464      1.149      0.280     -40.573     124.400
x4            35.1064     39.339      0.892      0.395     -53.884     124.097
x5             0.6484      0.506      1.282      0.232      -0.496       1.793
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

c:\Users\erena\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\stats\_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=14 observations were given.
  return hypotest_fun_in(*args, **kwds)

In [26]:
# x_train ve x_test 'den ilk sutünü çıkarıyoruz

x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]
#Tekrar sistemi eğitiyoruz
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)